version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: db_blog_strapi
    hostname: db_blog_strapi
    environment:
      POSTGRES_PASSWORD: mizu
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/.PostgressData/postgresonly/db_blog_strapi:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
